### ISSUE TITLE
The properties command doesn't work as expected

### ISSUE THREAD

**Issue by wdscxsj** [pdfcpu/pdfcpu#914] opened 2024-07-07 11:29 UTC
With pdfcpu v0.8.0 on Windows and the attached test file `in.pdf`, adding a Title property and a Author property works fine, which can be verified using Acrobat:

```
pdfcpu properties add in.pdf "Title = My Title" "Author = John Doe"
```

But listing properties shows nothing:

```
pdfcpu properties list in.pdf
```

And removing all properties also fails to work, because Acrobat still shows the property values:

```
pdfcpu properties remove in.pdf
```

![Screenshot366](https://github.com/pdfcpu/pdfcpu/assets/863369/d13a04f1-6213-4354-a222-c9a2e49c7400)

[in.pdf](https://github.com/user-attachments/files/16118976/in.pdf)

**Comment by hhrutter** [comment] 2024-07-07 12:10
Hello and thanks for reporting this!

Did you create your inputfile with Adobe?
Do you think you can share your input file?

**Comment by wdscxsj** [comment] 2024-07-07 12:43
Hello, the input file was attached at the end. It's actually identical to the `empty.pdf` file submitted in #912, generated from an empty file using [Typst](https://github.com/typst/typst).

**Comment by hhrutter** [comment] 2024-07-16 09:13
This works as intended:

'pdfcpu property list' will only output custom properties.

There are  info dict properties defined by the PDF specification:
`"Title", "Author", "Subject", "Keywords", "Creator", "Producer", "CreationDate", "ModDate", "Trapped"`

You can add custom properties, but these are generally considered not to be the standard info dict properties.

As an exception the CLI allows to set "Title", "Author", "Subject", "Creator" but these will only show up in the output
of `pdfcpu info'.

Likewise you can only remove custom properties.

I am sorry this may be a little bit confusing, but that's the current state of things.

In any case this needs and will to be documented on pdfcpu.io

**Comment by wdscxsj** [comment] 2024-07-16 10:21
Thanks for the detailed explanation! I can adjust my workflow accordingly.

**Comment by hhrutter** [comment] 2024-07-18 08:14
`"Title", "Author", "Subject", "Creator"` may now be added or removed using the CLI.

**Comment by wdscxsj** [comment] 2024-07-18 08:36
Thank you! I think the new feature is handy and works great.

But a remaining (and somewhat unrelated) issue is that CJK text is not handled well. For example, let's add an author to the original `in.pdf` (where 孔子 means Confucius in English):

```
pdfcpu properties add in.pdf "Author = 孔子"
```

pdfcpu lists the author properly, but not Acrobat:

![Screenshot368](https://github.com/user-attachments/assets/01e945d7-cd03-46de-ae40-bd6946c9f89f)

I've tried this on both Windows and Linux, with the same outcome.

**Comment by hhrutter** [comment] 2024-08-05 15:20
This should be fixed - go get the latest commit!

**Closed by hhrutter** 2024-08-05 15:20 UTC

**Comment by wdscxsj** [comment] 2024-08-05 20:28
Thanks a lot! Fix confirmed.
