### ISSUE TITLE
does pdfcpu support embed font into pdf?

### ISSUE THREAD

**Issue by liming-coder** [pdfcpu/pdfcpu#219] opened 2020-08-31 06:29 UTC
i want to create a text watermark with custom chinese font "SimSun", such as "test测试". the watermark is added but chinese text can't display. i guess the needed glyphs are not exacted and embedded into the target pdf.
how can i achieve this with pdfcpu?
thanks.

**Comment by hhrutter** [comment] 2020-08-31 07:10
Not yet.
#171 will address your issue.

**Comment by hhrutter** [comment] 2020-09-03 20:47
Closing duplicate of #171

**Closed by hhrutter** 2020-09-03 20:47 UTC
