### ISSUE TITLE
extract images: option raw  

### ISSUE THREAD

**Issue by kpym** [pdfcpu/pdfcpu#189] opened 2020-05-17 20:18 UTC
It looks like the `CCITT` images are recompressed and exported as `.png`.  Is it possible to export them as `.tiff` without recompression ?

**Comment by hhrutter** [comment] 2020-05-18 21:01
Hi!

Right now pdfcpu decodes CCITT image streams and writes them to PNG unless the ColorSpace is CMYK - in which case it writes the image to TIFF.

It makes sense and it is certainly possible to skip image decoding for CCITT streams and write out TIFF images directly but pdfcpu image extraction is experimental at best, it takes a lot of shortcuts to produce image files quickly.

One of the decisions was that PNG is more popular these days than TIFF and that's also the reason why right now pdfcpu writes CCITT based images to TIFF only if there isn't any other option like for color space CMYK based images. The other more selfish reason was that I wanted to explore CCITT compression in Go and the result was [x/image/ccitt](https://github.com/golang/image/tree/master/ccitt).

So overall I am hesitant to default to TIFF in the case of CCITT based images. The reason being less the performance impact of decoding/encoding but more the practical one that TIFF is an exotic image format these days and most people will prefer PNG over TIFF.

Acknowledging the use case for going straight to TIFF I am planning on making this a pdfcpu configuration option.

**Comment by kpym** [comment] 2020-05-19 06:24
Configuration option like `raw` to export image streams without decoding/encoding is a good idea. This will make extraction faster and lossless. In this way you can obtain `jpg`, `png`, `tiff` (for `ccitt` and `jbig2`) and `jp2` or `jpx` (for `jpeg2000`).

**Comment by hhrutter** [comment] 2020-06-28 13:51
I like the idea of having an option to bypass CCITT decoding when extracting images but there are some serious obstacles.
Generally in order to write a TIFF image tiff.Encode(f, img, nil) you need to supply the image pixels/data.
That's also what pdfcpu is already doing when writing CMYK images to TIFF.
Unfortunately as of now the tiff package does not support writing a TIFF image using CCITT(Group3,Group4) compression.

**Comment by kpym** [comment] 2020-06-28 14:51
It is strange that TIFF package do not support neither encoding neither raw stream writing as there are options for  `CCITTGroup3` , `CCITTGroup4` encoding in the `Encode` function.

I understand that the encoder in the TIFF package depends on the encoder in the CCITT package. But IMO there are missing `RawWrite` and `RawRaed` function in the `TIFF` package. TIFF is just a container so allowing raw stream read/write seems to me more natural than reading/writing using some encoder. There should be such raw read/write methods that are used internally after/before the image is encoded/decoded by the corresponding CCITT/JPEG package. 
This also can be even more useful for `jpeg` encoding in TIFF container because `jpeg` is not lossless and encoding/decoding is not idempotent action.

We can hope that the TIFF package will make public such raw read/write methods that will allow to change the container (tiff,jpeg,pdf) without encoding/decoding.

**Comment by hhrutter** [comment] 2020-06-28 17:27
Since I am one of the authors of x/image/ccitt I can confirm that the tiff writer is lacking ccitt compression support because the ccitt writer is still work in progress.

Other than that I encourage you to file a feature request [here](https://github.com/golang/go/issues) and prefix your issue subject with `x/image:` The current design of the tiff package is based on roundtripping `image.Image` structs to tiff and back most likely because it is part of the image repo.
 ;)

Whether it makes sense for image/tiff to support writing of already compressed image data is up for discussion I guess.

I cc
@bsiegert 
@nigeltao

**Comment by kpym** [comment] 2020-06-28 17:43
@hhrutter Done https://github.com/golang/go/issues/39900.

**Comment by hhrutter** [comment] 2020-07-02 20:50
I am going to close this for now since it diverged to golang/go/x/image

**Closed by hhrutter** 2020-07-02 20:50 UTC
Labels: enhancement
