### ISSUE TITLE
Possibly malformed file

### ISSUE THREAD

**Issue by eduardonunesp** [pdfcpu/pdfcpu#227] opened 2020-09-18 15:19 UTC
Failed to open a pdf file, the file seems to be working on MacPreview and Adobe Reader, on the terminal it gives an error when trying to validate.

```bash
validating(mode=relaxed) mypdf.pdf ...
validation error: validateDictEntry: dict=rootDict entry=AcroForm invalid type
```

```bash
pdfcpu version
pdfcpu: v0.3.5 dev
```

**Comment by hhrutter** [comment] 2020-09-18 16:11
This is a tough one.
This seems to be corrupt to me.
The root dict has a pointer to an Acrobat form dict, but there is only an integer.
Also there is no info dict containing the PDF writer that produced this.

**Comment by eduardonunesp** [comment] 2020-09-18 16:39
Yeh, I was trying with PDFBox a month ago and it opens but failed when trying to sign using the PDFBox signature

**Comment by hhrutter** [comment] 2020-09-18 16:58
If this is ok with you I would like to file this PDF under defect and close this issue.

**Comment by eduardonunesp** [comment] 2020-09-18 17:21
I think the error on the sign is because that bad formation that you commented above about the door dict point to an integer

```java
Exception in thread "main" java.lang.ClassCastException: org.apache.pdfbox.cos.COSInteger cannot be cast to org.apache.pdfbox.cos.COSDictionary
	at org.apache.pdfbox.pdmodel.PDDocumentCatalog.getAcroForm(PDDocumentCatalog.java:108)
	at org.apache.pdfbox.pdmodel.PDDocument.addSignature(PDDocument.java:308)
	at br.com.testsigner.CreateSignature.signDetached(CreateSignature.java:166)
	at br.com.testsigner.CreateSignature.signDetached(CreateSignature.java:118)
	at br.com.testsigner.CreateSignature.main(CreateSignature.java:281)
```

**Comment by hhrutter** [comment] 2020-09-18 19:25
OK, I am closing this.

**Closed by hhrutter** 2020-09-18 19:25 UTC

**Comment by eduardonunesp** [comment] 2020-09-18 19:42
Are you sure, that same PDF file runs on others platforms, maybe it's ok to ignore an unexpected type like that

**Comment by hhrutter** [comment] 2020-09-18 19:52
A PDF showing this kind of symptom is suspicious to me.
Even more so because there is no info dict, which is not forbidden but highly unusual.
If there was a way to reproduce this kind of artifact for me, I would reconsider.
