### ISSUE TITLE
Replace image

### ISSUE THREAD

**Issue by lz1998** [pdfcpu/pdfcpu#455] opened 2022-04-20 18:45 UTC
I want to translate images in a pdf. After translation, the images will be the same size, but I don't know how to replace them.

**Comment by hhrutter** [comment] 2022-04-21 22:39
I think this is something pdfcpu can provide as long as the image dimensions remain constant.

Maybe something like:
```
pdfcpu extract -mode image in.pdf .
...
writing img_#32.png
# alter image
...
pdfcpu image update #32 in.pdf in_#32.jpg
```

**Comment by adamgreenhall** [comment] 2022-04-28 18:14
👍 I would also like to use this.

**Comment by GwynethLlewelyn** [comment] 2024-09-06 11:02
Just to be sure, this feature hasn't been implemented yet, correct? Not even in an experimental/alpha branch?

**Comment by hhrutter** [comment] 2024-09-08 09:15
🧑‍🔬 not yet, tricky but not forgotten..

**Comment by GwynethLlewelyn** [comment] 2024-09-11 19:26
Hehe thanks, just checking! Then it _must_ be really tricky. I would _love_ to take a look at it (I _do_ have a case where I "urgently" need to switch a static image by an animated one, and this is anything but trivial with the toolset I've got), but I'm afraid this would require a lot of time. I've not completely given up the idea, though; I love Go (the more I learn to use it, the more I love it!) and would find the challenge quite interesting.

Alas, don't hold your breath, my Go programming abilities (as well as my time!) are terribly limited...

But on the other side of the coin, few PDF "processing" tools seem to offer the richness of `pdfcpu`, and I keep coming back to it to do the simplest things (such as merging two PDFs together or adding comments/keywords/attachments/properties), which, weirdly enough, few tools do, and even fewer **command-line** tools do. Oh well! Thanks for the great work.

**Comment by hhrutter** [comment] 2024-09-12 22:56
Your welcome!
I'll see to it that this makes it into one of the next releases.

**Comment by adamgreenhall** [comment] 2024-09-26 15:03
@GwynethLlewelyn how are you doing on this? I've also been thinking about looking into this and would love to find out anything you've learned

**Comment by hhrutter** [comment] 2024-10-05 17:21
Folks... I am 💥 happy💥  to report this turned into a new command:

```
$ pdfcpu pdfcpu images
usage: pdfcpu images list    [-p(ages) selectedPages] -- inFile...
       pdfcpu images extract [-p(ages) selectedPages] -- inFile outDir
       pdfcpu images update inFile imageFile [outFile] [ objNr | (pageNr Id) ]

Manage images.

     pages ... Please refer to "pdfcpu selectedpages"
    inFile ... input PDF file
 imageFile ... image file
   outFile ... output PDF file
     objNr ... obj# from "pdfcpu images list"
    pageNr ... Page from "pdfcpu images list"
        Id ... Id from "pdfcpu images list"

    Example: pdfcpu images list gallery.pdf
             gallery.pdf:
             1 images available (1.8 MB)
             Page Obj# │ Id  │ Type  SoftMask ImgMask │ Width │ Height │ ColorSpace Comp bpc Interp │   Size │ Filters
             ━━━━━━━━━━┿━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━┿━━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━━┿━━━━━━━━━━━━
                1    3 │ Im0 │ image                  │  1268 │    720 │  DeviceRGB    3   8    *   │ 1.8 MB │ FlateDecode

             # Extract all images into the current dir
             pdfcpu images extract gallery.pdf .
             extracting images from gallery.pdf into ./ ...
             optimizing...
             writing gallery_1_Im0.png

             # Update image with Id=Im0 on page=1 with gallery_1_Im0.png
             pdfcpu images update gallery.pdf gallery_1_Im0.png
             pdfcpu images update gallery.pdf gallery_1_Im0.png out.pdf

             # Update image object 3 with logo.png
             pdfcpu images update gallery.pdf logo.png 3
             pdfcpu images update gallery.pdf logo.png out.pdf 3

             # update image with Id=Im0 on page=1 with logo.jpg
             pdfcpu images update gallery.pdf logo.jpg 1 Im0
             pdfcpu images update gallery.pdf logo.jpg out.pdf 1 Im0
```

🧑‍🔬 Waiting for your valuable feedback before this makes it into the next release..

**Comment by GwynethLlewelyn** [comment] 2024-10-07 10:59
First and foremost — thank you so much! This seems to fit like a glove for 99% of the use cases out there, namely the one pointed out by @lz1998 — the ability to slightly change images, keeping the layout. And this works as expected!

There is just one additional use case which I have: the ability to have _differently-named files_ — which may even have different extensions altogether. Here is the simplest example: I have a catalogue with lots of 'heavy' images, and 'regular' PDF image compression utilities only go so far in reducing their size. Instead, I export them all from the PDF using `pdfcpu`, upload the images to the popular [TinyPNG](https://tinypng.com) online image compression utility, and download them as lossless WebP. Lossless PNG magically become 30x (that's 30 _times_, not 30%!) smaller. And now I want to replace these images on the PDF.

Unfortunately, that won't work, since the extension name gets changed, and, without a new extension, PDF viewers will choke on the format (at least, some of them will, they don't bother to check for the 'magic' attribute and make their decisions depending solely on the file extension). I therefore wonder what is involved in actually changing the **name** (and, implicitly, the image format) while keeping the size and positioning data exactly in the same place.

But there is more :-)

The PDF specifications have no strict limitations in the image _formats_. It's just by _convention_ that we use the ancient formats JPEG, PNG, etc. Most interestingly, instead of embedding a movie in a PDF (which works well, it's part of the recent specifications), you can use animated images, such as provided by the GIF, PNG and WebP formats. Yay! But sadly _no_ tool I use to generate PDFs is able to recognise that animated format — although _most_ viewers (either web-embedded or native standalone apps) will have no problem in rendering such 'special' images. As a rule of thumb, if you can view a certain image natively on your browser (i.e., without requiring extra codecs, plugins, extensions, etc.), then the PDF is almost certainly also going to work. Nevertheless, GIFs are the safest bet (they always are), but `pdfcpu` doesn't even support those.

Surprisingly, Adobe Acrobat has some _limited_ support for animated images. In other words, you _can_ use them when tinkering around with the PDF's layout. It's just that when _saving_ or _exporting_, since Adobe Acrobat is still tailored for _printing_ PDFs, only the first frame is retained.

`pdfcpu` to the rescue!... or at least that's what I hoped to use. Given that the names cannot be changed — let's assume this is a built-in limitation on the PDF format which will _never_ be overcome; I can live with that — the easiest way is to do your layout using non-animated GIF or PNG, create the PDF as usual, and then replace the image using `pdfcpu` with its animated variant. Ta-da! 🎺 

Well, not quite:

1. GIF is unsupported by `pdfcpu`, so any attempts to replace GIFs will fail with the appropriate error.
2. Animated PNG is a superset of PNG. `pdfcpu`, therefore, is able to correctly identify the PNG format as one of the supported formats. However, when actually _reading_ the file, it stumbles upon the additional frames embedded in the Animated PNG (APNG) file, and given an obscure error ( `pdfcpu: unknown image object for objNr=XX`).

I haven't tried this out with WebP animations yet (who knows, it _might_ work) simply because _that_ frame-animation format is even less known or supported (a pity, really).  Anything out there will handle GIF files. Most will also start to accept Animated PNG. especially since Apple actively endorsed APNG for its stickers. WebP animation is a big question mark here, since I only know that Google Chrome supports it (or at least some variants do).

So... are you able to figure out a workaround? :)

**Comment by adamgreenhall** [comment] 2024-10-07 18:24
@hhrutter sounds great! but I think there is something off, at least on my machine. getting the error message `unknown image object for objNr ...` on every attempt. Checked and I'm even getting that error on the `TestUpdateImages` test case. I'm on dc38554a2a84e3e3d14978f3df87e417ab772d72

**Comment by petervwyatt** [comment] 2024-10-08 00:22
> The PDF specifications have no strict limitations in the image formats. It's just by convention that we use the ancient formats JPEG, PNG, etc. Most interestingly, instead of embedding a movie in a PDF (which works well, it's part of the recent specifications), you can use animated images, such as provided by the GIF, PNG and WebP formats. Yay! But sadly no tool I use to generate PDFs is able to recognise that animated format — although most viewers (either web-embedded or native standalone apps) will have no problem in rendering such 'special' images. As a rule of thumb, if you can view a certain image natively on your browser (i.e., without requiring extra codecs, plugins, extensions, etc.), then the PDF is almost certainly also going to work. Nevertheless, GIFs are the safest bet (they always are), but pdfcpu doesn't even support those.

**This is incorrect.** The official PDF specifications when both proprietary Adobe and now as ISO standard ISO 32000 since 2008 have **_always explicitly defined_** which compression and image codecs/formats are valid in (valid) PDF files. Most are just codecs since the overhead of image files is unnecessary and duplicates the required PDF metadata and is thus stripped off leaving just the codec data. None of them have ever allowed animation (keyframe or otherwise) in PDF files - e.g. an animated GIF cannot be stored as an on-page moving image in a valid PDF file. Moving images can only be achieved via PDF annotation objects (Sound, Movie, 3D, or RichMedia - depending on PDF version) or simulated trickery with JS and very much which viewer and platform is used. Of course, s/w can easily transcode any image format to one of the many (static) PDF codecs but internally to the PDF file, the data is entirely different. Alternatively, you might embed an animated GIF file (for example) in a PDF where it is not an image in page content, but is an embedded file stream object (of various kinds, where the file bitstream is precisely preserved) then _some_ viewers _may_ preview it - but this is not "on any page" and varies greatly by implementation, and platform as it is outside the scope of the official file format specifications. Mileage will definitely vary.

**Comment by GwynethLlewelyn** [comment] 2024-10-08 02:14
Whoops. I stand corrected. Actually, I should have checked first before making a stupid and incorrect statement. My apologies. There was a reason for the wrong assumption, though; I incorrectly assumed that, since PDFs don't 'embed' images directly, but rather convert them first to an internal representation, the file format itself would be irrelevant and up to the viewer to decide what it supports and what it doesn't.

But you're absolutely correct, and I was totally wrong in those assumptions. While the actual internal representation might, indeed, be the "raw" image data — stripped from whatever metadata the image envelope or container might add — and optionally compressed, just keeping a few common elements as metadata — there are clear information regarding how certain image formats are to be handled, and these are present even on the PDF 1.0 specification; back in 1993, it sufficed to assume that image data was either lossless (and coming from a high-resolution TIFF file) or lossy (as produced by JPEG): anything else could, in a way or another be converted to either format. Thus, the focus was on giving support to those formats (I believe there were a few others which would also get "special treatment", but these two were the major ones).

But by the time PDF 1.4 became common, other formats were explicitly added to the specification, namely, PNG, which has its own extra goodies (namely, additional predictors for the lossless compression algorithm). I didn't do a thorough research, but it seems quite clear to me that formats such as GIF (even non-animated) were never even mentioned and deemed irrelevant — they could easily be converted first to a different format and reused later. PNG might have been much more important to support 'natively', so to speak, most probabl because it became part of the W3C specifications for browsers rendering images inside HTML (and was also unencumbered by patents, unlike other file formats); PNG effectively displaced TIFF, as it can be seen, in a sense, as a superset of TIFF — which is certainly true when considering a _single_ image or frame — as it can use most of the features that TIFF supports while adding several of its own.

I didn't check if the 2.0 specifications mention Web3, or even HEIF or AVI, since these, in a sense, are next-generation image file formats which _might_ require extra handling information.

Whatever the _exact_ list of file formats might be, one thing is now certain to me: clearly, my assumptions were wrong, and no, you cannot embed "any" image file format in a PDF and expect it to work. That's not how the specs define the format. Also, technically speaking, even if the filename is now preserved (it wasn't on the earliest versions of the PDF specifications) as well as some metadata, allowing tools such as `pdfcpu` to 'extract' images from a PDF file, such 'extraction' is not an exact duplicate of the original, and will necessarily differ (often considerably), since, during the creation of the PDF file, the "raw" data has to be extracted first before being written; all sorts of compression or encoding tricks originally supported by the image file format will thus be "lost", unless there are "hints" for such "tricks" in the image metadata. However, in the absence of those, it's more likely that only single-image PNG (or possibly JPEG) can be extracted directly from a PDF. You _can_ convert it further to other formats, of course, but that happens outside the scope of the PDF specifications, as an additional, extraneous step. But from the perspective of the viewer application, none of that is really necessary: only the raw data — what will be displayed on screen or printed on paper — is required.

Therefore, even a viewer that is able to display such things as animated images or other fancy transformations cannot do much with what the PDF will contain, in terms of data. It's also irrelevant what the application that generated the PDF supports or not; even if generator and viewer both agree on certain file formats and what is supposed to do with them, PDF, by itself, is almost agnostic, by storing raw image data, without relation to the actual data contained in the original image files. As such, there is no obvious way of doing any "magic tricks" with special tags or embedded instructions on an image file, since none of that will "survive" a conversion to PDF.

This should actually have been obvious to me; after all, the P in PDF stands for **portable**, in the sense that it is a _universal_ file format, without having to rely upon assumptions regarding the many components that have been brought into a document.

And with that, I conclude three weeks of wasting my time trying to do something which is clearly impossible but which I stubbornly persisted to 'prove' otherwise 😁 Oh well. It wasn't the first time, and it most certainly won't be the last. And I'm always learning new things anyway. 

In any case, I just wanted to thank @adamgreenhall for his tip. I also had an ancient `config.yml` — the one originally installed by Homebrew, I suppose — and that's why I got the above-mentioned error. After properly replacing it with the default, everything worked as expected.

That said, as far as I'm concerned, this issue is closed for me — `pdfcpu` works exactly as intended and as expected, within what is possible to do with the PDF format. It might just be worth adding a note somewhere (on the README, possibly!) that the `config.yml` should be kept up to date, lest some operations start to fail for completely unrelated reasons.

Thanks @hhrutter for all your work, as well as your patience to explain how things are _really_ supposed to work!

**Comment by petervwyatt** [comment] 2024-10-08 04:55
@GwynethLlewelyn - I can openly state that there is [active technical work](https://pdfa.org/community/imaging-model-twg/) looking to include HDR content, JPEG-XL, AVIF, Brotli, and other similar features into a future version of PDF. But many of these have larger consequences to the PDF imaging model.

**Comment by beeing** [comment] 2024-12-11 00:47
Hi @hhrutter thanks for the new `images` command, the extract works great.

However, I noticed that there's no batch command to  perform `images update` from the directory that was extracted to.

Will be nice to have the `pdfcpu images update source.pdf imagesDir` which based on the extracted filenames to update the images back to the PDF.

Thanks in advance.

**Comment by hhrutter** [comment] 2024-12-11 08:51
@beeing Please create a separate new feature issue with a clear description.

Thank you!

**Closed** 2024-12-11 08:52 UTC
Labels: feature request
