### ISSUE TITLE
split: error during optimization

### ISSUE THREAD

**Issue by lukaskund** [pdfcpu/pdfcpu#393] opened 2021-11-09 16:58 UTC
Hey, 

Nice tool. Recently we started to use it for splitting on larger volume and noticed that it pretty often panics at [parseContent.go:139](https://github.com/pdfcpu/pdfcpu/blob/master/pkg/pdfcpu/parseContent.go#L139) line. Unfortunately I can't share the documents due sensitive data in them, so for now pasting only the stack trace. If I can help with anything else - let me know.

BTW those docs are openable / viewable in readers and they can be splitted using poppler-utils `pdfseparate` command.

` [{"path":"github.com/aws/aws-lambda-go@v1.22.0/lambda/errors.go","line":39,"label":"lambdaPanicResponse"},{"path":"github.com/aws/aws-lambda-go@v1.22.0/lambda/function.go","line":36,"label":"(*Function).Invoke.func1"},{"path":"runtime/panic.go","line":965,"label":"gopanic"},{"path":"runtime/panic.go","line":88,"label":"goPanicIndex"},{"path":"github.com/pdfcpu/pdfcpu@v0.3.12/pkg/pdfcpu/parseContent.go","line":139,"label":"skipBI"},{"path":"github.com/pdfcpu/pdfcpu@v0.3.12/pkg/pdfcpu/parseContent.go","line":204,"label":"positionToNextContentToken"},{"path":"github.com/pdfcpu/pdfcpu@v0.3.12/pkg/pdfcpu/parseContent.go","line":225,"label":"nextContentToken"},{"path":"github.com/pdfcpu/pdfcpu@v0.3.12/pkg/pdfcpu/parseContent.go","line":324,"label":"parseContent"},{"path":"github.com/pdfcpu/pdfcpu@v0.3.12/pkg/pdfcpu/xreftable.go","line":1582,"label":"consolidateResources"},{"path":"github.com/pdfcpu/pdfcpu@v0.3.12/pkg/pdfcpu/xreftable.go","line":1621,"label":"(*XRefTable).processPageTreeForPageDict"},{"path":"github.com/pdfcpu/pdfcpu@v0.3.12/pkg/pdfcpu/xreftable.go","line":1656,"label":"(*XRefTable).processPageTreeForPageDict"},{"path":"github.com/pdfcpu/pdfcpu@v0.3.12/pkg/pdfcpu/xreftable.go","line":1682,"label":"(*XRefTable).PageDict"},{"path":"github.com/pdfcpu/pdfcpu@v0.3.12/pkg/pdfcpu/pages.go","line":128,"label":"AddPages"},{"path":"github.com/pdfcpu/pdfcpu@v0.3.12/pkg/pdfcpu/extract.go","line":472,"label":"(*Context).ExtractPages"},{"path":"github.com/pdfcpu/pdfcpu@v0.3.12/pkg/api/split.go","line":69,"label":"writePageSpan"},{"path":"github.com/pdfcpu/pdfcpu@v0.3.12/pkg/api/split.go","line":114,"label":"writePageSpans"},{"path":"github.com/pdfcpu/pdfcpu@v0.3.12/pkg/api/split.go","line":155,"label":"Split"}]
`

**Comment by hhrutter** [comment] 2021-11-09 20:33
Thanks for reporting this!
Any sample file you can share for further analysis would help big time resolving this.

**Comment by hhrutter** [comment] 2021-11-30 10:26
Hi!
A small sample file in order to reproduce this would help a lot fixing this.

**Comment by hhrutter** [comment] 2021-12-01 08:16
Resource id analysis is now turned off by default for the split command.
You should not be getting this error anymore.

**Comment by hhrutter** [comment] 2022-03-25 22:12
Closed due to inactivity.

**Closed by hhrutter** 2022-03-25 22:12 UTC
Labels: bug
