### ISSUE TITLE
Regression: broken layout after watermark/split

### ISSUE THREAD

**Issue by mrtnmtth** [pdfcpu/pdfcpu#238] opened 2020-10-16 12:57 UTC
I got a multi-page PDF file for which the `watermark` function produces a broken layout in the resulting file. The broken layout can also be reproduced using `split`.

There are no errors using `validate` and `optimize` does not change the result either.

The affected source PDF file used to work fine prior to release v0.3.6

[pdfcpu-split-log-v0.3.5.log](https://github.com/pdfcpu/pdfcpu/files/5391650/pdfcpu-split-log-v0.3.5.log)
[pdfcpu-split-log-v0.3.6.log](https://github.com/pdfcpu/pdfcpu/files/5391653/pdfcpu-split-log-v0.3.6.log)

**Comment by hhrutter** [comment] 2020-10-16 13:23
Sorry, there is no way for me to analyze your issue without a sample PDF file.
Log analysis is not enough in such a scenario.

**Comment by mrtnmtth** [comment] 2020-10-16 13:24
I will mail you the sample file

**Comment by mrtnmtth** [comment] 2020-10-21 19:58
I dug into the issue a little more to find commit 4f10ad0e8a7bd44a2d0d9ae707c472a843cb4e9f being the cause of the regression.

With some crude `fmt.Println()` debugging I was able to pinpoint the issue to the function `parseContent()`. There are some `XObject` and `Font` attributes missing from the returned `PageResourceNames`.


```
*Working*
[Page 1]
PageResourceNames:
XObject: Im0, Im1, Im2, Im3, Im4
Font: C2_2, C2_3, C2_4, C0_0, C0_3, C2_0, C2_1, C0_1, C0_2, C2_5, C2_6
[Page 2]
PageResourceNames:
XObject: Im0, Im1, Im2, Im3
Font: C2_0, C2_1, C0_0, C2_2, C2_3, C2_4, C2_5
----------------------
*Broken*
[Page 1]
PageResourceNames:
XObject: Im1, Im0
Font: C0_0
[Page 2]
PageResourceNames:
XObject: Im0
Font: C2_0
```

**Comment by hhrutter** [comment] 2020-10-21 21:43
I already have an idea about the cause of this but I would need the files for further analysis and a fix.
The heart of the problem is the page content parsing for identification of actual usage of page resources.
Please send them over if you can.
Thank you

**Comment by mrtnmtth** [comment] 2020-10-23 07:11
Did you get my mail this time?

**Comment by hhrutter** [comment] 2020-10-23 18:48
Nope.
Sorry my bad, there was a typo in my email address that is now fixed.
It's the address on my [profile](https://github.com/hhrutter)

**Closed** 2020-11-07 00:59 UTC
Labels: bug

**Comment by hhrutter** [comment] 2020-11-07 10:29
Fixed with latest commit!

**Comment by mrtnmtth** [comment] 2020-11-09 08:26
Works fine now. Thanks a lot.
