### ISSUE TITLE
Form fields containing diacritics not displaying correctly

### ISSUE THREAD

**Issue by bretwalker** [pdfcpu/pdfcpu#773] opened 2024-01-11 15:17 UTC
Using:
pdfcpu: v0.6.0 dev
commit: https://github.com/pdfcpu/pdfcpu/commit/e33b502b4fe35a2b7fceb2e1e5c9d2fdd4446d34 (2023-12-13T10:22:47Z)
base : go1.21.0

On macOS 13.6 (22G120)

When I populate a form with text containing text with diacritics, it is not rendered properly in Adobe Acrobat Pro 2023.008.20458 when opened. The text does appear as expected once I click on the form field in Acrobat Pro.

<img width="498" alt="Screenshot 2024-01-11 at 10 14 37 AM" src="https://github.com/pdfcpu/pdfcpu/assets/181698/5cff43e5-d106-4282-a150-9fc7b0333ec3">

<img width="471" alt="Screenshot 2024-01-11 at 10 14 44 AM" src="https://github.com/pdfcpu/pdfcpu/assets/181698/887ddd05-f1eb-440a-be4e-8eb5eedb87c5">

If I edit populate the form using either Acrobat or macOS Preview using the same text as is in the JSON, the file opens as expected in Acrobat.

[out.json](https://github.com/pdfcpu/pdfcpu/files/13905010/out.json)
[populated.out.json](https://github.com/pdfcpu/pdfcpu/files/13905011/populated.out.json)
[template-pl.pdf](https://github.com/pdfcpu/pdfcpu/files/13905012/template-pl.pdf)
[template.pdf](https://github.com/pdfcpu/pdfcpu/files/13905014/template.pdf)

**Comment by hhrutter** [comment] 2024-02-07 23:44
The cause of this is that this PDF form defines the fill font to be a Type 1 core font.
For fill strings containing code points above 0xFF this results in these characters to disappear because they can't be represented by any glyph. 

The solutions for this is embedding a font which contains these missing glyphs.

**Comment by hhrutter** [comment] 2024-02-10 11:41
This is fixed with latest commit.

**Closed** 2024-02-10 11:41 UTC
Labels: investigate
