### ISSUE TITLE
writeStream: missing eol before keyword endstream

### ISSUE THREAD

**Issue by Blesmol** [pdfcpu/pdfcpu#285] opened 2021-01-25 22:41 UTC
I'm currently using the pdfcpu golang api (v0.3.6) and came across an error that I was also able to reproduce using the latest release (v0.3.8), both from golang api as well as using the standalone pdfcpu executable on win64.

When extracting a single page out of a PDF document and opening the resulting file in PDF XChange Editor (Free version), it complains that there would be an error in the XREF table. It still displays the PDF. Opening the same file in Acrobat Reader or xpdf does not yield any errors, so I do not know whether this might only be a small issue or perhaps even wrong alert.

I tested this with different PDF documents from different sources. Also checked that the original documents from which I extracted the pages did not show any error when opening in PDF XChange Editor.

The command that I used to extract was nothing special: `pdfcpu.exe extract -m page -p 1 input.pdf outputDir`. Please find attached a sample input and output file from testing.

[input.pdf](https://github.com/pdfcpu/pdfcpu/files/5870094/input.pdf)
[input_page_1.pdf](https://github.com/pdfcpu/pdfcpu/files/5870095/input_page_1.pdf)

**Comment by hhrutter** [comment] 2021-01-25 23:47
Hi there!

The extracted file looks fine to me:
```
Go-> pdfcpu val input_page_1.pdf
validating(mode=relaxed) input_page_1.pdf ...
validation ok

Go-> pdfcpu info input_page_1.pdf
         PDF version: 1.7
          Page count: 1
           Page size: 21.59 x 27.94 cm
............................................
               Title:
              Author:
             Subject:
        PDF Producer: pdfcpu 0.3.8
     Content creator:
       Creation date: D:20210125233306+01'00'
   Modification date: D:20210125233306+01'00'
............................................
              Tagged: No
              Hybrid: No
          Linearized: No
  Using XRef streams: Yes
Using object streams: Yes
         Watermarked: No
............................................
           Encrypted: No
         Permissions: Full access
Go->
```

I am happy to look into this but what is the specific complaint of the software you are using?
Adobe Reader and Mac Preview - both serve as reference PDF viewers for pdfcpu  - also don't seem to have a problem with it.

Just validate your file with `pdfcpu validate` if you have doubts about the validity of a PDF file.

Thank you for using pdfcpu 💚

**Comment by Blesmol** [comment] 2021-01-26 08:22
Hi,

Unfortunately, this is really the full error message presented by PDF XChange, see screenshot :-/ I will try to reproduce with a minimal PDF and also try to spot differences here. Might also be that PDF XChange provides some means to repair whatever it complains about, perhaps this will bring additional insights. Will report back as soon as I have something new.

![2021-01-26_09-18-12](https://user-images.githubusercontent.com/9559347/105818835-aa8db680-5fb7-11eb-9050-d5b0b37a034e.png)

**Comment by Blesmol** [comment] 2021-01-26 08:47
I did some additional tests, but not sure how much this helps.

What I did:
1. Created small PDF file: [`minimal.pdf`](https://github.com/pdfcpu/pdfcpu/files/5872113/minimal.pdf) => No error in PDFXchange 
2. Extracted page using pdfcpu v0.3.8 using command liste above: [`minimal_page_1.pdf`](https://github.com/pdfcpu/pdfcpu/files/5872114/minimal_page_1.pdf) => Error in PDFXchange that XREF table would have errors
3. Used PDFXChange to autofix this: [`minimal_page_1_repaired_by_pdfxchange.pdf`](https://github.com/pdfcpu/pdfcpu/files/5872115/minimal_page_1_repaired_by_pdfxchange.pdf) => No error when opening this in PDFXchange
4. Used `pdftk` to uncompress file `minimal_page_1.pdf` to check whether the error also appears in the uncompressed version: [`minimal_page_1_uncompressed_by_pdftk_no_error.pdf`](https://github.com/pdfcpu/pdfcpu/files/5872116/minimal_page_1_uncompressed_by_pdftk_no_error.pdf) => No error when opening this in PDFXChange
5. Used `pdftk` to generate a copy of the file without further operations (`pdftk minimal_page_1.pdf output minimal_page_1_pdftk.pdf`): [`minimal_page_1_pdftk.pdf`](https://github.com/pdfcpu/pdfcpu/files/5872148/minimal_page_1_pdftk.pdf) => No error when opening this in PDFXChange

Unfortunately I currently do not know what else I could check here. Although I do have a little bit of knowledge about the PDF format and the XREF table, I fear this is not sufficient for further analysis from my side, sorry :-(

**Comment by Blesmol** [comment] 2021-01-26 08:57
I also checked some online PDF validators with the erroneous file. Most of them were quite happy. One of them complained.

https://freetoolonline.com/preflight-pdf.html for `minimal_page_1.pdf`:
```
    1.2.2: Body Syntax error, Expected 'EOL' before the endstream keyword at offset 924 but found '101'
    1.2.2: Body Syntax error, Expected 'EOL' before the endstream keyword at offset 566 but found '101'
    1.4: Trailer Syntax error, /XRef cross reference streams are not allowed
    2.4.3: Invalid Color space, The operator "G" can't be used without Color Profile
    2.4.3: Invalid Color space, The operator "g" can't be used without Color Profile
    3.1.1: Invalid Font definition, Helvetica: some required fields are missing from the Font dictionary: firstChar, lastChar, widths.
    3.1.3: Invalid Font definition, Helvetica: FontFile entry is missing from FontDescriptor
    7.1: Error on MetaData, Missing Metadata Key in catalog
    1.2.5: Body Syntax error, Stream length is invalid [cObj=COSObject{3, 0}; defined length=115; buffer2=endstream e]
    1.2.5: Body Syntax error, Stream length is invalid [cObj=COSObject{7, 0}; defined length=249; buffer2=endstream e]
```

As I do not know which of these might actually be related to what pdfcpu is doing here, I also tried the same using the initial `minimal.pdf` file:
```
    1.1: Header Syntax error, Second line must begin with '%' followed by at least 4 bytes greater than 127
    1.4.7: Trailer Syntax error, EmbeddedFile entry is present in the Names dictionary
    1.4.1: Trailer Syntax error, The trailer dictionary doesn't contain ID
    2.4.3: Invalid Color space, The operator "G" can't be used without Color Profile
    2.4.3: Invalid Color space, The operator "g" can't be used without Color Profile
    3.1.1: Invalid Font definition, Helvetica: some required fields are missing from the Font dictionary: firstChar, lastChar, widths.
    3.1.3: Invalid Font definition, Helvetica: FontFile entry is missing from FontDescriptor
    7.1: Error on MetaData, Missing Metadata Key in catalog
```

From the erroneous file especially the `Stream length is invalid` looks suspicious I would say...

**Comment by hhrutter** [comment] 2021-01-26 10:59
Yes might be related to the stream length calculation.

**Comment by hhrutter** [comment] 2021-01-28 00:45
The stream length calculation is fine but there was a missing eol post stream data.
Thanks! Good catch 💚

**Comment by Blesmol** [comment] 2021-01-30 14:40
Hi,

Thanks for the fix. I downloaded and compiled the recent source and gave it another try. Unfortunately, it seems that PDFXchange is still complaining. The online checker above does no longer complain about the stream, but there is still the error about invalid XRef cross reference streams... is that something that should also be looked into?

```
    1.4: Trailer Syntax error, /XRef cross reference streams are not allowed
    2.4.3: Invalid Color space, The operator "G" can't be used without Color Profile
    2.4.3: Invalid Color space, The operator "g" can't be used without Color Profile
    3.1.1: Invalid Font definition, Helvetica: some required fields are missing from the Font dictionary: firstChar, lastChar, widths.
    3.1.3: Invalid Font definition, Helvetica: FontFile entry is missing from FontDescriptor
    7.1: Error on MetaData, Missing Metadata Key in catalog
```

[minimal_page_1_with_fix.pdf](https://github.com/pdfcpu/pdfcpu/files/5898119/minimal_page_1_with_fix.pdf)

**Comment by hhrutter** [comment] 2021-01-30 22:52
`1.4: Trailer Syntax error, /XRef cross reference streams are not allowed`
I don't know, I did not find anything releated to this in the spec.
Maybe somebody else can shed some light. /cc @petervwyatt

I am also not sure if this should be worrysome.
Up to now I have not heard any parser complaint of that sort.

pdfcpu writes xref streams per default.
Have you tried reconfiguring pdfcpu so it writes regular xref sections?
`pdfcpu version -v` points you to the config dir then edit config.yml and set `writeXRefStream: false`.

**Comment by petervwyatt** [comment] 2021-01-31 06:12
@hhrutter I can see one issue with the XRef stream dict in `input_page_1.pdf`: the /Size value and /Index array 2nd element do not match. I believe the Index 2nd array element is off by one - it's 28 but should be 29.

- **Size**: (_Required_) The number one greater than the highest object number used in this section or in any section for which this shall be an update. It shall be equivalent to the Size entry in a trailer dictionary.

- **Index**: (_Optional_) An array containing a pair of integers for each subsection in this section. The first integer shall be the first object number in the subsection; the second integer shall be the number of entries in the subsection
The array shall be sorted in ascending order by object number. Subsections cannot overlap; an object number shall have no more than one entry in a section.
Default value: [0 _Size_].

`pdfcpu validate -v --mode strict input_pdf_1.pdf` acknowledges this:
```

validating(mode=strict) input_page_1.pdf ...
 INFO: 2021/01/31 17:09:03 PDF Version 1.5 conforming reader
 INFO: 2021/01/31 17:09:03 validating
STATS: 2021/01/31 17:09:03 XRefTable:
*************************************************************************************************
HeaderVersion: 1.7
has 1 pages
using object streams
using xref streams
XRefTable:
                     Size: 29
              Root object: (1 0 R)
              Info object: (26 0 R)
                ID object: [<A8BFBCFC165CE47A95BF2C2C744E58CF> <A8BFBCFC165CE47A95BF2C2C744E58CF>]
XRefTable with 29 entres:
...
```

**Comment by petervwyatt** [comment] 2021-01-31 06:24
Regarding if an EOL is required before the **endstream** keyword - ISO 32000 does _not_ explicitly require this. 
However it has become a relatively common custom for many PDF writers as there are so many broken PDF parsers out there that need this.

Related is a statement in "Table 5 - Entries common to all stream dictionaries" also states in the description of the **Length** key: "(There may be an additional EOL marker, preceding **endstream**, that is not included in the count and is not logically part of the stream data.)" - so you shouldn't have to tweak your Length logic if you prepend an EOL to **endstream**.

**Comment by hhrutter** [comment] 2021-01-31 10:06
Thanks for your suggestions!

So all my findings and work going into pdfcpu is based on the ISO spec: PDF 32000:1 2008 

This docuemnt defines for Index: *... the second integer shall be the number of entries in the subsection...*
pdfcpu does exactly this starting with obj#0 but it cannot account for the obj# needed for the xref stream dict
because that itself is not part of it. The issue is that the xref entry needed for the xref stream dict is included in *Size*
so the default for index `[0 Size]` as stated by the spec does not make sense to me.

Regarding the EOL issue:
I think the spec contradicts itself here since I can verify your quote from Table 5 but a couple of pages before
at 7.3.8.1 of PDF 32000:1 2008 the spec says:

*... The sequence of bytes that make up a stream lie between the end-of-line marker following the stream keyword and the endstream keyword; the stream dictionary specifies the exact number of bytes. There should be an end-of-line marker after the data and before endstream; this marker shall not be included in the stream length. ...*

**Comment by petervwyatt** [comment] 2021-02-01 00:06
(Personal opinion) I would not treat ISO 32000-1:2008 so much like gospel. It was a very rapid conversion of the existing Adobe spec to ISO format/style back in 2007/2008 and thus retained many issues - such as these kinds inconsistencies. Only later was ISO 32000-2 developed under a true consensus-based and open process, with a huge number of clarifying changes to make a more level playing field... which is one reason it also took so long! And this was just one of them... (including the para you point out which was also corrected and aligned). 
Treat ISO 32000-2 as the combined efforts of many experts over many years to correct many long-standing issues that were in the Adobe docs and thus apply equally to all versions of PDF.

The [0 Size] and /Size is just how it's always been :-)

**Comment by hhrutter** [comment] 2021-02-01 10:40
👍  Understood.

As pdfcpu states right now it conforms to ISO 32000-1:2008 so we can only compromise.
It also means we have to take mentioned above parser complaint with a grain of salt
and only once we provide ISO 32000-2 compatibility get these treated properly.

**Comment by hhrutter** [comment] 2021-02-12 23:56
The detected issue is fixed.
I am closing this but the remaining XChange Editor complaints still need to be investigated extensively.

**Closed by hhrutter** 2021-02-12 23:56 UTC

**Comment by hhrutter** [comment] 2021-02-17 00:22
The remaining issue XChange Editor was complaining about is fixed with the latest commit.

**Comment by Blesmol** [comment] 2021-02-17 16:36
Thanks! I can confirm that the validation error in PDF XChange is now gone. Great work!
