### ISSUE TITLE
pdfcpu: user font not loaded: HelveticaLTStd-Bold\n

### ISSUE THREAD

**Issue by owenhankinson** [pdfcpu/pdfcpu#767] opened 2024-01-08 23:00 UTC
### Thank you for submitting a possible bug!

Please ensure the following:

* Your issue is based on the latest commit
- using v0.5.0 
* State your OS and OS version
 - Circle Ci container - ubuntu0.22.04.1

Me and my team run tests to ensure the PDFCPU fill methods are doing what we expect them to. We have a flakey issue where tests will fail with this error from PDFCPU - `pdfcpu: user font not loaded: HelveticaLTStd-Bold`. We end up just rerunning the test and it succeeds. Is there any way to prevent this from stopping our tests as often as it does?

**Comment by hhrutter** [comment] 2024-01-08 23:54
OK, what do you expect them to do?
Please describe a representative use case for your scenario and if possible share a test file in order to reproduce and fix this.

Thank you so much!

**Comment by owenhankinson** [comment] 2024-01-09 16:50
@hhrutter We are using PDFCPU to fill in various government forms. I have downloaded them in our repo so that we use the same copy every time we export the form values. The error is hard to track down why its happening, we are not using any configuration for fonts, but it is for sure happening on the `form fill` command (more likely). The only tools we are using from the CLI is `export`, and `fill`. I've attached a copy of one of the blank i-9 forms we use.

Here is a snippet of the GO code that is run when this error occurs:
```
	cmd := exec.Command("pdfcpu", "form", "fill", PDFFilePath, inputJSONFilePath, PDFFilePath)

	stderr, err := cmd.StderrPipe()
	if err != nil {
		log.Println(err)
		return err
	}

	if err := cmd.Start(); err != nil {
		log.Println(err)
		return err
	}

	errBytes, err := ioutil.ReadAll(stderr)
	if err != nil {
		log.Println(err)
		return err
	}

	if len(errBytes) > 0 {
		log.Println(string(errBytes))
		return errors.New(string(errBytes))
	}
```

Note: When using the CLI locally, I have never encountered this issue, just when Circle CI runs the tests.

### files
[blank-i9-2023.pdf](https://github.com/pdfcpu/pdfcpu/files/13876612/blank-i9-2023.pdf)
[blank-w4-2023.pdf](https://github.com/pdfcpu/pdfcpu/files/13876613/blank-w4-2023.pdf)

**Comment by hhrutter** [comment] 2024-01-09 17:20
Understood!
Before I take a closer look, will I be able to repoduce your error by trying to fill one of these 2 ?
Just to ensure your CI/CD env is not the culprit here.

**Comment by hhrutter** [comment] 2024-01-09 17:44
try this: https://github.com/pdfcpu/pdfcpu/releases/tag/v0.6.0

**Comment by owenhankinson** [comment] 2024-01-09 17:48
@hhrutter the only reason we don't want to move to 0.6.0 is so I don't have to go through and redefine all of the fields for these forms. Moving to 0.6.0 changes the IDs of the fields generated by export. I opened an issue to just see if there was a fix for disabling something in the CLI that I didn't know of. Just so we don't have tests fail so much

**Comment by hhrutter** [comment] 2024-01-09 17:54
There were a couple of major bugs fixed in the last release regarding form filling.
I strongly recommend upgrading.

Specifying a custom font for filling is in the pipeline: see #715

**Comment by owenhankinson** [comment] 2024-01-18 17:39
@hhrutter reopening this issue. Been on the latest PDFCPU version for about a week now and still seeing the same tests fail with the same error. The CLI command "form fill" seems to still be giving us this font not loaded error. Is there any way for us to get around this?

Thanks again!

**Comment by hhrutter** [comment] 2024-01-31 18:31
So where are you getting this error now? 
On the command line, only in CircleCI? or the api?
Can you paste a stacktrace?
Can you help me reproducing this?

**Comment by owenhankinson** [comment] 2024-01-31 18:42
@hhrutter yes! Only happening in Circle CI, I cannot reproduce in my own shell. 
```
json tools test fill json function [BeforeEach] fills the form with correct information
  [BeforeEach] /home/circleci/go/src/github.com/bookreport/api/operations/w4_json_tools_test.go:330
  [It] /home/circleci/go/src/github.com/bookreport/api/operations/w4_json_tools_test.go:347

  [FAILED] Unexpected error:
      <*errors.errorString | 0xc000050c00>: 
      pdfcpu: user font not loaded: HelveticaLTStd-Bold
      
      {
          s: "pdfcpu: user font not loaded: HelveticaLTStd-Bold\n",
      }
  occurred
  In [BeforeEach] at: /home/circleci/go/src/github.com/bookreport/api/operations/w4_json_tools_test.go:344 @ 01/31/24 18:12:32.094
```

**Comment by owenhankinson** [comment] 2024-01-31 18:44
Like I said above this is the code that is running when the error occurs

> `Here is a snippet of the GO code that is run when this error occurs:

	cmd := exec.Command("pdfcpu", "form", "fill", PDFFilePath, inputJSONFilePath, PDFFilePath)

	stderr, err := cmd.StderrPipe()
	if err != nil {
		log.Println(err)
		return err
	}

	if err := cmd.Start(); err != nil {
		log.Println(err)
		return err
	}

	errBytes, err := ioutil.ReadAll(stderr)
	if err != nil {
		log.Println(err)
		return err
	}

	if len(errBytes) > 0 {
		log.Println(string(errBytes))
		return errors.New(string(errBytes))
	}
`

**Comment by hhrutter** [comment] 2024-01-31 18:59
👍🏻 I am aware, but I still need to see a stacktrace.

We need to narrow this down somehow..

So if you fill your PDF on the CLI this is working?

Also we have `TestFillForm` in form_test.go
Please go ahead and patch this test so it uses your data.
I need to know if the filling via API is working as intended generally for your testcase/file and fillinf json

On a side note: Why use `exec` (which may very well be the issue here)  from Go when you can use the pdfcpu API?

**Comment by hhrutter** [comment] 2024-02-06 23:17
Assuming that the font `HelveticaLTStd-Bold` is loaded into your std pdfcpu config
but can't be located in your CircleCI env this could also be an issue with your pdfcpu config path.

You can set the path to your config dir using `-conf` on the cmd line.
Check the bottom of: https://pdfcpu.io/getting_started/config_dir

**Closed** 2024-05-20 07:37 UTC
Labels: investigate

**Comment by hhrutter** [comment] 2024-05-20 07:38
This is fixed with the latest commit!
