### ISSUE TITLE
write: line length overflow

### ISSUE THREAD

**Issue by kaiceo** [pdfcpu/pdfcpu#357] opened 2021-07-20 08:38 UTC
i got a err "Read: xRefTable failed: bufio.Scanner: token too long", when adding annotations to a merged pdf with 9900 pages
the err occur in func tryXRefSection after debugging

**Comment by hhrutter** [comment] 2021-07-20 09:41
Thank you for reporting this.
I will need more information on this.
I need to know your use case, whar kind of annotations you added and how.
Further I need to see a stacktrace that you can also produce with `pdfcpu val -vv in.pdf`
.. and please if possible get me a sample PDF in order to reproduce this. 9900 pages is a lot..

**Comment by kaiceo** [comment] 2021-07-21 01:36
Use case:
1. convert many html files to seperated pdf files by [go-wkhtmltopdf ](https://github.com/SebastiaanKlippert/go-wkhtmltopdf)
2. merge pdf files to single pdf by api.MergeCreateFile
3. Implementation a new LinkAnnotation interface in my project package for replacing pdf internal uri link, core code below:
             
               type LinkAnnotation struct {
	                      pdfcpu.Annotation
                      
	                      Dest *pdfcpu.IndirectRef
                      }
              func (ann *LinkAnnotation) RenderDict(pageIndRef pdfcpu.IndirectRef) pdfcpu.Dict {
              
	              d := pdfcpu.Dict(map[string]pdfcpu.Object{
		              "Type":    pdfcpu.Name("Annot"),
		              "Subtype": pdfcpu.Name(ann.TypeString()),
		              "Rect":    ann.Rect.Array(),
		              "P":       pageIndRef,
		              "F":       pdfcpu.Integer(ann.F),
		              "Border":  pdfcpu.NewIntegerArray(0, 0, 1), // no border
		              "H":       pdfcpu.Name("I"),                // default
		              "Dest":    pdfcpu.Array{*ann.Dest, pdfcpu.Name("XYZ"), pdfcpu.Integer(0), pdfcpu.Integer(841), pdfcpu.Integer(0)},
	              })
              
	              if ann.NM != "" {
		              d.InsertString("NM", ann.NM)
	              }
              
	              if ann.C != nil {
		              d.Insert("C", pdfcpu.NewNumberArray(float64(ann.C.R), float64(ann.C.G), float64(ann.C.B)))
	              }
	              return d
              }
4. catching all internal links in single pdf,  convert to map[int][]pdfcpu.AnnotationRenderer  for func api.AddAnnotationsMapFile
5. Then run.
6. simple pdf and annotations json file
[ann.txt](https://github.com/pdfcpu/pdfcpu/files/6852169/ann.txt)

[a62019-2768763.pdf](https://github.com/pdfcpu/pdfcpu/files/6852164/a62019-2768763.pdf)

7. Could support chinese(CJK) bookmarks ?(too lazy to open new issue....)， Itseems to api.InstallFonts not valid for bookmarks.

**Comment by hhrutter** [comment] 2021-07-21 16:33
I don't see any stacktrace but it is going to be difficult to help you regardless, since it does not look like you are using the current api to add annotations. You are doing something different, exactly what is also not fully clear.

If you are looking for a solution for a special usecase that you like to see covered by pdfcpu,
please open a feature request issue and make sure you state your complete usecase in all details required for a possible implementation. 

Another example for opening a separate issue would be "bookmarks: font support".

Thank you for using pdfcpu 💚  
& please consider becoming a sponsor.
Your potential sponsorship ensures pdfcpu does not go stale over the long run like many other projects.

**Comment by kaiceo** [comment] 2021-07-22 01:27
opt.pdf with 9900 pages is merged by func api.MergeCreatedFile
stracktrace is below：
      
      [root@10 htmlManualProcesser]# ./pdfcpu val -vv opt.pdf
      validating(mode=relaxed) opt.pdf ...
       READ: 2021/07/21 21:23:39 Read: begin
       INFO: 2021/07/21 21:23:39 PDF Version 1.5 conforming reader
       READ: 2021/07/21 21:23:39 readXRefTable: begin
      Fatal: pdfcpu: can't find last xref section
      github.com/pdfcpu/pdfcpu/pkg/pdfcpu.offsetLastXRefSection
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/read.go:169
      github.com/pdfcpu/pdfcpu/pkg/pdfcpu.readXRefTable
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/read.go:1291
      github.com/pdfcpu/pdfcpu/pkg/pdfcpu.Read
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/read.go:74
      github.com/pdfcpu/pdfcpu/pkg/api.ReadContext
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/api.go:48
      github.com/pdfcpu/pdfcpu/pkg/api.Validate
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/validate.go:43
      github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/validate.go:92
      github.com/pdfcpu/pdfcpu/pkg/cli.Validate
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/cli/cli.go:33
      github.com/pdfcpu/pdfcpu/pkg/cli.Process
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/cli/process.go:35
      main.process
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/process.go:91
      main.processValidateCommand
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/process.go:133
      main.commandMap.process
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/cmd.go:143
      main.main
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/main.go:55
      runtime.main
              /Users/horstrutter/gotip/src/runtime/proc.go:225
      runtime.goexit
              /Users/horstrutter/gotip/src/runtime/asm_amd64.s:1371
      Read: xRefTable failed
      github.com/pdfcpu/pdfcpu/pkg/pdfcpu.Read
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/read.go:75
      github.com/pdfcpu/pdfcpu/pkg/api.ReadContext
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/api.go:48
      github.com/pdfcpu/pdfcpu/pkg/api.Validate
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/validate.go:43
      github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/validate.go:92
      github.com/pdfcpu/pdfcpu/pkg/cli.Validate
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/cli/cli.go:33
      github.com/pdfcpu/pdfcpu/pkg/cli.Process
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/cli/process.go:35
      main.process
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/process.go:91
      main.processValidateCommand
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/process.go:133
      main.commandMap.process
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/cmd.go:143
      main.main
              /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/main.go:55
      runtime.main
              /Users/horstrutter/gotip/src/runtime/proc.go:225
      runtime.goexit
              /Users/horstrutter/gotip/src/runtime/asm_amd64.s:1371

**Comment by hhrutter** [comment] 2021-07-22 07:50
If I understand correctly you merge some files into a big file and then add annotations.
First we need to find out if adding annotations causes problems or the fact that you are merging big files.
Please check for me the following in that sequence and report back the results.

1) Merge your files again but don't add anotations and check if pdfcpu validation succeeds.
if validation succeeds, adding annotation has a problem.

2) Can you open opt.pdf (before or after adding annots but AFTER merging) with Adobe Reader or MacPreview?
If it opens, the pdfcpu parser needs some work.
if it does not open the xref stream creation in the pdfcpu writet needs some work.

3) set writeXRefStream: false in pdfcpu config.yml (`pdfcpu ver -vv`tells you the location) and execute your whole workflow again. Then check if opt.pdf opens up in Adobe Reader and only the check pdfcpu validation: `pdfcpu val opt.pdf`or `pdfcpu info opt.pdf` 

4) Retry your whole workflow, but with smaller files and see if anything changes.

Please report back your findings so I can fix this.
Thank you

**Comment by kaiceo** [comment] 2021-07-22 12:44
two file : opt1.pdf(3226 pages)
open software: Adobe Acrobat Pro

### Step1.  Merged , dont add annotations
validation ok, acrobat open ok

### Step 2. remove annotation , Add annotations, use origin func
===============================================
remove anns ok,
add ann err : Read: xRefTable failed: bufio.Scanner: token too long

//remove annotation output == input file

    	err = api.RemoveAnnotationsFile("opt1.pdf", "opt1.pdf", []string{"even", "odd"}, nil, nil, pdfcpu.NewDefaultConfiguration(), true)
	if err != nil {
		fmt.Println("remove ann err :", err)
	}

	err = api.AddAnnotationsFile("opt1.pdf", "opt1.pdf", []string{"even", "odd"}, pdfcpu.NewLinkAnnotation(*pdfcpu.Rect(50, 150, 100, 300),
		nil, "https://www.google.com", "googleid", pdfcpu.AnnNoZoom, nil), pdfcpu.NewDefaultConfiguration(), true)
	if err != nil {
		fmt.Println("add ann err :", err)
	}
  =============================================
remove anns ok, add anns ok
//remove annotation output != input file

	err = api.RemoveAnnotationsFile("opt1.pdf", "opt1_out.pdf", []string{"even", "odd"}, nil, nil, pdfcpu.NewDefaultConfiguration(), true)
	if err != nil {
		fmt.Println("remove ann err :", err)
	}

	err = api.AddAnnotationsFile("opt1_out.pdf", "opt1_out.pdf", []string{"even", "odd"}, pdfcpu.NewLinkAnnotation(*pdfcpu.Rect(50, 150, 100, 300),
		nil, "https://www.google.com", "googleid", pdfcpu.AnnNoZoom, nil), pdfcpu.NewDefaultConfiguration(), true)
	if err != nil {
		fmt.Println("add ann err :", err)
	}
=============================================
remove anns ok, add anns ok
//remove annotation output == input file, increase = false


	    err = api.RemoveAnnotationsFile("opt1.pdf", "opt1.pdf", []string{"even", "odd"}, nil, nil, pdfcpu.NewDefaultConfiguration(), false)
	    if err != nil {
		    fmt.Println("remove ann err :", err)
	    }
    
	    err = api.AddAnnotationsFile("opt1.pdf", "opt1.pdf", []string{"even", "odd"}, pdfcpu.NewLinkAnnotation(*pdfcpu.Rect(50, 150, 100, 300),
		    nil, "https://www.google.com", "googleid", pdfcpu.AnnNoZoom, nil), pdfcpu.NewDefaultConfiguration(), false)
	    if err != nil {
		    fmt.Println("add ann err :", err)
	    }

### other testing is going on

**Comment by kaiceo** [comment] 2021-07-22 12:48
file : opt1.pdf(3226 pages)
open software: Adobe Acrobat Pro

### Step1.  Merged , dont add annotations
validation ok, acrobat open ok

### Step 2. remove annotation , Add annotations, use origin func
===============================================
remove anns ok,
add ann err : Read: xRefTable failed: bufio.Scanner: token too long

//remove annotation output == input file

    	err = api.RemoveAnnotationsFile("opt1.pdf", "opt1.pdf", []string{"even", "odd"}, nil, nil, pdfcpu.NewDefaultConfiguration(), true)
	if err != nil {
		fmt.Println("remove ann err :", err)
	}

	err = api.AddAnnotationsFile("opt1.pdf", "opt1.pdf", []string{"even", "odd"}, pdfcpu.NewLinkAnnotation(*pdfcpu.Rect(50, 150, 100, 300),
		nil, "https://www.google.com", "googleid", pdfcpu.AnnNoZoom, nil), pdfcpu.NewDefaultConfiguration(), true)
	if err != nil {
		fmt.Println("add ann err :", err)
	}
  =============================================
remove anns ok, add anns ok
//remove annotation output != input file

	err = api.RemoveAnnotationsFile("opt1.pdf", "opt1_out.pdf", []string{"even", "odd"}, nil, nil, pdfcpu.NewDefaultConfiguration(), true)
	if err != nil {
		fmt.Println("remove ann err :", err)
	}

	err = api.AddAnnotationsFile("opt1_out.pdf", "opt1_out.pdf", []string{"even", "odd"}, pdfcpu.NewLinkAnnotation(*pdfcpu.Rect(50, 150, 100, 300),
		nil, "https://www.google.com", "googleid", pdfcpu.AnnNoZoom, nil), pdfcpu.NewDefaultConfiguration(), true)
	if err != nil {
		fmt.Println("add ann err :", err)
	}
=============================================
remove anns ok, add anns ok
//remove annotation output == input file, increase = false


	    err = api.RemoveAnnotationsFile("opt1.pdf", "opt1.pdf", []string{"even", "odd"}, nil, nil, pdfcpu.NewDefaultConfiguration(), false)
	    if err != nil {
		    fmt.Println("remove ann err :", err)
	    }
    
	    err = api.AddAnnotationsFile("opt1.pdf", "opt1.pdf", []string{"even", "odd"}, pdfcpu.NewLinkAnnotation(*pdfcpu.Rect(50, 150, 100, 300),
		    nil, "https://www.google.com", "googleid", pdfcpu.AnnNoZoom, nil), pdfcpu.NewDefaultConfiguration(), false)
	    if err != nil {
		    fmt.Println("add ann err :", err)
	    }

### other testing is going on, hope bookmark font supported as soon as possible, so that i can test more func

**Comment by hhrutter** [comment] 2021-07-22 21:07
You are writing increments to your file.
Once for the annotation removal pass and then again after adding annotations.
Since you are dealing with a huge file with around 10000 pages and edit annotations for every single page,
the result is that pdfcpu has to rewrite a sequence of 10000 non contiguous objects eg 2,4,6,8,10 etc. for every PDF increment with the consequence that the xref streamdict's Index attribute is an array with around 10000 entries.

🥇 Thank you for discovering a bug where pdfcpu does not respect the 255 chars per line limit for PDF objects other than streams. 💚 

Generally though I recommend you reconsider producing PDFs with 10000 pages.
Without going into any detail with that kind of file size you are in questionable territory where all sorts of limits could bite you at any given time.

Although I can understand the choice for writing annotations for a large file in PDF increments instead of rewriting the whole file, the idea to allow writing annotations via PDF increments is for small increments like for PDF signatures or maybe a couple of annotations and changes here and there.

So even once this bug is fixed I recommend you implement your annotation editing usecase with a small Go programm 
where you read in the xref table and then iterate once over your pages and take care of your annotations and then write back everything - once. This will be much faster since the xref table will be loaded once instead of right now twice.

I have 2 quick workarounds for you until this is fixed:

* Turn off increments when adding/removing annotations via the api. 
* reconfigure pdfcpu so it doesn not write xref streams but the classical xref sections. 
  (like explained above: set writeXRefStream: false in pdfcpu config.yml (pdfcpu ver -vvtells you the location))

**Comment by hhrutter** [comment] 2022-04-11 08:45
If you merged your files using pdfcpu please use the suggested workaround from #451

**Closed** 2022-04-11 22:13 UTC
Labels: bug

**Comment by hhrutter** [comment] 2022-04-11 22:18
I am pretty sure the very reason for this issue is that you merged a lot  of files using pdfcpu's default configuration.
This results in quite long lines which made the parser choke when using bufio.Scanner.
This is now fixed with latest commit!
